name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04 # Corrected spelling
    steps:
      - name: Say Hello
        run: |
          echo "Hello World!"
      - name: Date
        run: |
          date
      - name: Directory contents
        run: |
          ls
